server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:

            # User Service
            - id: user-service
              uri: lb://USER-SERVICE
              predicates:
                - Path=/api/users/**

            # Event Service
            - id: event-service
              uri: lb://EVENT-SERVICE
              predicates:
                - Path=/api/events/**

            # Booking Service
            - id: booking-service
              uri: lb://BOOKING-SERVICE
              predicates:
                - Path=/api/bookings/**

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server-container:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway